// Copyright 2024 Example Corp. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by stringer. DO NOT EDIT.

package main

var generatedDoc = "this file was generated"
