package discovery

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ingo/agent-readyness/pkg/types"
)

func TestClassifyGoFile(t *testing.T) {
	tests := []struct {
		name     string
		filename string
		want     types.FileClass
	}{
		{"regular source main.go", "main.go", types.ClassSource},
		{"regular source handler.go", "handler.go", types.ClassSource},
		{"test file main_test.go", "main_test.go", types.ClassTest},
		{"test file handler_test.go", "handler_test.go", types.ClassTest},
		{"underscore prefix ignored", "_ignored.go", types.ClassExcluded},
		{"dot prefix hidden", ".hidden.go", types.ClassExcluded},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ClassifyGoFile(tt.filename)
			if got != tt.want {
				t.Errorf("ClassifyGoFile(%q) = %v, want %v", tt.filename, got, tt.want)
			}
		})
	}
}

func TestIsGeneratedFile(t *testing.T) {
	// Create temp files for testing
	tmpDir := t.TempDir()

	// File with generated header on first line
	firstLineGenerated := filepath.Join(tmpDir, "first_line.go")
	writeFile(t, firstLineGenerated, `// Code generated by protoc-gen-go. DO NOT EDIT.

package main
`)

	// File with copyright header THEN generated comment before package
	copyrightThenGenerated := filepath.Join(tmpDir, "copyright_then_gen.go")
	writeFile(t, copyrightThenGenerated, `// Copyright 2024 Example Corp. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by stringer. DO NOT EDIT.

package main
`)

	// Regular Go source file
	regularFile := filepath.Join(tmpDir, "regular.go")
	writeFile(t, regularFile, `package main

func main() {}
`)

	// File with DO NOT EDIT after package declaration (should NOT be detected)
	afterPackage := filepath.Join(tmpDir, "after_package.go")
	writeFile(t, afterPackage, `package main

// Code generated by foo. DO NOT EDIT.
func main() {}
`)

	tests := []struct {
		name string
		path string
		want bool
	}{
		{"generated header on first line", firstLineGenerated, true},
		{"generated after copyright header", copyrightThenGenerated, true},
		{"regular source file", regularFile, false},
		{"DO NOT EDIT after package declaration", afterPackage, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := IsGeneratedFile(tt.path)
			if err != nil {
				t.Fatalf("IsGeneratedFile(%q) unexpected error: %v", tt.path, err)
			}
			if got != tt.want {
				t.Errorf("IsGeneratedFile(%q) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}
