package discovery

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ingo-eichhorst/agent-readyness/pkg/types"
)

func TestClassifyGoFile(t *testing.T) {
	tests := []struct {
		name     string
		filename string
		want     types.FileClass
	}{
		{"regular source main.go", "main.go", types.ClassSource},
		{"regular source handler.go", "handler.go", types.ClassSource},
		{"test file main_test.go", "main_test.go", types.ClassTest},
		{"test file handler_test.go", "handler_test.go", types.ClassTest},
		{"underscore prefix ignored", "_ignored.go", types.ClassExcluded},
		{"dot prefix hidden", ".hidden.go", types.ClassExcluded},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := classifyGoFile(tt.filename)
			if got != tt.want {
				t.Errorf("classifyGoFile(%q) = %v, want %v", tt.filename, got, tt.want)
			}
		})
	}
}

func TestClassifyPythonFile(t *testing.T) {
	tests := []struct {
		name     string
		filename string
		want     types.FileClass
	}{
		{"regular source app.py", "app.py", types.ClassSource},
		{"regular source utils.py", "utils.py", types.ClassSource},
		{"test prefix test_app.py", "test_app.py", types.ClassTest},
		{"test suffix app_test.py", "app_test.py", types.ClassTest},
		{"test prefix test_utils.py", "test_utils.py", types.ClassTest},
		{"conftest is source", "conftest.py", types.ClassSource},
		{"underscore prefix", "_private.py", types.ClassExcluded},
		{"dot prefix", ".hidden.py", types.ClassExcluded},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := classifyPythonFile(tt.filename)
			if got != tt.want {
				t.Errorf("classifyPythonFile(%q) = %v, want %v", tt.filename, got, tt.want)
			}
		})
	}
}

func TestClassifyTypeScriptFile(t *testing.T) {
	tests := []struct {
		name     string
		filename string
		want     types.FileClass
	}{
		{"regular source index.ts", "index.ts", types.ClassSource},
		{"regular source app.tsx", "app.tsx", types.ClassSource},
		{"test file index.test.ts", "index.test.ts", types.ClassTest},
		{"spec file index.spec.ts", "index.spec.ts", types.ClassTest},
		{"test tsx file App.test.tsx", "App.test.tsx", types.ClassTest},
		{"spec tsx file App.spec.tsx", "App.spec.tsx", types.ClassTest},
		{"underscore prefix", "_internal.ts", types.ClassExcluded},
		{"dot prefix", ".config.ts", types.ClassExcluded},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := classifyTypeScriptFile(tt.filename)
			if got != tt.want {
				t.Errorf("classifyTypeScriptFile(%q) = %v, want %v", tt.filename, got, tt.want)
			}
		})
	}
}

func TestIsGeneratedFile(t *testing.T) {
	// Create temp files for testing
	tmpDir := t.TempDir()

	// File with generated header on first line
	firstLineGenerated := filepath.Join(tmpDir, "first_line.go")
	writeFile(t, firstLineGenerated, `// Code generated by protoc-gen-go. DO NOT EDIT.

package main
`)

	// File with copyright header THEN generated comment before package
	copyrightThenGenerated := filepath.Join(tmpDir, "copyright_then_gen.go")
	writeFile(t, copyrightThenGenerated, `// Copyright 2024 Example Corp. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by stringer. DO NOT EDIT.

package main
`)

	// Regular Go source file
	regularFile := filepath.Join(tmpDir, "regular.go")
	writeFile(t, regularFile, `package main

func main() {}
`)

	// File with DO NOT EDIT after package declaration (should NOT be detected)
	afterPackage := filepath.Join(tmpDir, "after_package.go")
	writeFile(t, afterPackage, `package main

// Code generated by foo. DO NOT EDIT.
func main() {}
`)

	tests := []struct {
		name string
		path string
		want bool
	}{
		{"generated header on first line", firstLineGenerated, true},
		{"generated after copyright header", copyrightThenGenerated, true},
		{"regular source file", regularFile, false},
		{"DO NOT EDIT after package declaration", afterPackage, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := isGeneratedFile(tt.path)
			if err != nil {
				t.Fatalf("isGeneratedFile(%q) unexpected error: %v", tt.path, err)
			}
			if got != tt.want {
				t.Errorf("isGeneratedFile(%q) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}
